# Generated by Django 2.0.6 on 2018-06-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20180624_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='remarks',
            field=models.TextField(default='Application submitted', null=True),
        ),
    ]
