# Generated by Django 2.0.6 on 2018-06-24 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20180624_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='paid_on',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='enter only date in yyyy/mm/dd format', null=True),
        ),
    ]
