# Generated by Django 2.0.6 on 2018-06-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20180624_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
