# Generated by Django 2.0.6 on 2018-06-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_fee_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='mobile_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
