# Generated by Django 2.0.6 on 2018-06-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20180625_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='mobile_no',
            field=models.CharField(default='', max_length=10),
        ),
    ]
