# Generated by Django 2.0.6 on 2018-06-25 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20180625_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='application',
            name='caste',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='college_address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='college_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='application',
            name='department',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='application',
            name='duration',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='application',
            name='internship_type',
            field=models.CharField(default='Training', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='residence_address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='year_of_study',
            field=models.CharField(default='Third', max_length=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fees',
            field=models.FloatField(default=200.0),
        ),
        migrations.AlterField(
            model_name='fee',
            name='paid_on',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='enter only date in yyyy/mm/dd format'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='transaction_no',
            field=models.CharField(default='', max_length=20),
        ),
    ]
