# Generated by Django 2.0.6 on 2019-07-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20180625_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='employee_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
