# Generated by Django 2.0.6 on 2019-07-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_slot_employee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
