# Generated by Django 2.0.6 on 2019-07-28 14:29

import django.core.validators
from django.db import migrations, models
import portal.validators


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_slot_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='caste',
        ),
        migrations.RemoveField(
            model_name='application',
            name='caste_certificate',
        ),
        migrations.RemoveField(
            model_name='application',
            name='college_address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='course',
        ),
        migrations.RemoveField(
            model_name='application',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='application',
            name='internship_type',
        ),
        migrations.RemoveField(
            model_name='application',
            name='noc',
        ),
        migrations.RemoveField(
            model_name='application',
            name='residence_address',
        ),
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.FileField(help_text='upload only pdf files', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf']), portal.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant_photo',
            field=models.FileField(help_text='upload jpg, jpeg, png files only', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg']), portal.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='application',
            name='year_of_study',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth')], default='1', max_length=1),
        ),
    ]
