# Generated by Django 2.0.6 on 2019-07-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20190728_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_no',
            field=models.CharField(default='00XX0000', max_length=11),
        ),
    ]
