# Generated by Django 2.0.6 on 2019-07-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20190731_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='application',
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
    ]
