# Generated by Django 2.0.6 on 2019-07-30 19:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20190731_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_receipt', models.FileField(help_text='upload pdf,jpg,jpeg,png files only with size less than 2mb', null=True, upload_to='')),
                ('fee_type', models.CharField(choices=[('O', 'Online'), ('C', 'Challan')], default='O', max_length=1)),
                ('transaction_no', models.CharField(default='', max_length=20)),
                ('fees', models.FloatField(default=200.0)),
                ('paid_on', models.DateTimeField(default=django.utils.timezone.now, help_text='enter only date in yyyy/mm/dd format')),
                ('is_fees_paid', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('remarks', models.TextField(null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.Application')),
            ],
        ),
    ]
