# Generated by Django 2.0.6 on 2018-06-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_applicant_is_group_formed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='mobile_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='official',
            name='mobile_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
