# Generated by Django 2.0.6 on 2019-07-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180625_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='department',
            field=models.CharField(choices=[('BT', 'Biotechnology'), ('CE', 'Civil Engineering'), ('CH', 'Chemical Engineering'), ('CS', 'Computer Science & Engineering'), ('EC', 'Electronics and Communication Engineering'), ('EE', 'Electrical Engineering'), ('IT', 'Information Technology'), ('ME', 'Mechanical Engineering'), ('MM', 'Metallurgical and Materials Engineering')], default='CS', max_length=2),
        ),
    ]
